import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import LeftSidebar from "@/components/LeftSidebar/page";
import RightSidebar from "@/components/RightSidebar/page";
import RenderChildren from "@/components/RenderChildren/page";
import Navbar from "@/components/Navbar/page";
import { Flip, ToastContainer, Zoom } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "../../../utils/authProvider";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Facebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [activeLeftSidebar, setActiveLeftSidebar] = useState(true);
  return (
    <html
      lang="en"
      className="p-0 m-0 box-border max-h-screen max-w-full overflow-hidden "
    >
      <head></head>
      <body
        className={` ${poppins.className} w-full h-full bg-backgroundColor `}
      >
        <AuthProvider>
          <header className="relative h-28 lg:h-16 ">
            {" "}
            <Navbar />{" "}
          </header>
          <main className="px-4 w-full flex-1 flex items-start  relative  ">
            <LeftSidebar />
            {/* <div className="w-full sm:w-1/2 lg:w-1/4 absolute lg:relative "></div> */}
            <div className="w-full md:w-3/4 xl:w-2/4  mr-0 md:mr-3 lg:mr-0  h-[calc(100vh-136px)] xl:h-[calc(100vh-88px)]  ">
              <ToastContainer
                position="bottom-left"
                autoClose={5000}
                hideProgressBar
                newestOnTop={false}
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
                transition={Flip}
              />
              {/* {children} */}
              <RenderChildren children={children} />
            </div>
            <div className=" md:w-1/4 hidden md:block ">
              <RightSidebar />
            </div>
          </main>
          {/* <footer className="h-2 ">
            <p>Copyright clam @ {Date()}</p>
          </footer> */}
        </AuthProvider>
      </body>
    </html>
  );
}
